# Generated by Django 2.2.6 on 2019-11-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pdfupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfupload',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
